monorepo_root = true

[monorepo]
config_roots = [
    "build-image/"
]

[tools]
"github:stephane-klein/incus-apply" = { version = "v0.1.2-sklein-draft", bin = "incus-apply" }
"github:mitsuhiko/minijinja" = { version = "2.24.0", bin = "minijinja-cli" }

[shell_alias]
ssh = "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR"

[tasks.deploy-lxc]
run = """
set -euo pipefail

export NETBIRD_SETUP_KEY="$(gopass show -o netbird/setup-keys/incus-auto-group)"

minijinja-cli -a none --env incus-poc-lxc.yaml.j2 > incus-poc-lxc.yaml

scripts/purge-netbird-peers.sh incus-poc-lxc.yaml
incus-apply incus-poc-lxc.yaml
"""

[tasks.enter-in-lxc]
run = """
ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR fedora@foot-incus-ssh-tmux-osc52-poc.homelab.stephane-klein.info
"""
